# Taken from https://github.com/andyli/HaxeCI/blob/master/appveyor.yml
version: "{build}"

install:
    # http://help.appveyor.com/discussions/problems/5616-not-able-to-build-due-to-problem-in-chocolateyinstallps1
    - ps: Set-Service wuauserv -StartupType Manual
    - cinst haxe --version 4.2.5 -y
    # Setup haxelib
    - haxelib setup C:/haxelib
    # Install project dependencies
    - haxelib install hxcpp > /dev/null --quiet
    - haxelib install hmm --quiet
    - haxelib run hmm install

build_script:
    - haxelib run lime build windows

artifacts:
    - path: export/release/windows/bin
    name: windowsBuild
    type: zip