name: Build Release
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compile: [linux, mac, windows]
        build: [release, x86]

        exclude:
          - compile: linux
            build: x86

        include:
          - compile: linux
            os: ubuntu-latest
            folder: linux

          - compile: mac
            os: macOS-12
            folder: macos

          - compile: windows
            os: windows-latest
            folder: windows

    name: ${{ matrix.compile }}-${{ matrix.build }}
    permissions: write-all
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Restore action cache
        uses: actions/cache@main
        with:
          key: cache-${{ matrix.compile }}-${{ matrix.build }}
          path: |
            export/${{ matrix.build }}/${{ matrix.folder }}/haxe/
            export/${{ matrix.build }}/${{ matrix.folder }}/obj/
            .haxelib/
          restore-keys: |
            cache-${{ matrix.compile }}-${{ matrix.build }}

      - name: Setup Haxelib
        run: |
          haxelib setup .haxelib/
        
      - name: Install Hxcpp
        run: |
          git clone https://github.com/HaxeFoundation/hxcpp.git --depth=1;
          haxelib dev hxcpp hxcpp
          cd hxcpp/tools/hxcpp
          haxe compile.hxml
          cd ../../../

      - name: Installing/Updating libraries
        run: |
          haxe -cp commandline -D analyzer-optimize --run Main setup

      - name: Compile (x86)
        if: ${{ matrix.build == 'x86' }}
        run: haxelib run lime build ${{ matrix.compile }} -${{ matrix.build }} -D HXCPP_M32

      - name: Compile (x64)
        if: ${{ matrix.build != 'x86' }}
        run: haxelib run lime build ${{ matrix.compile }} -${{ matrix.build }}

      - name: Uploading artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.compile }}-${{ matrix.build }}
          path: export/${{ matrix.build }}/${{ matrix.folder }}/bin
          if-no-files-found: error

      - name: Clearing already existing cache
        uses: actions/github-script@main
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-${{ matrix.compile }}-${{ matrix.build }}") {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log("Cache cleared.")
              }
            }

      - name: Uploading new cache
        uses: actions/cache@main
        with:
          key: cache-${{ matrix.compile }}-${{ matrix.build }}
          path: |
            export/${{ matrix.build }}/${{ matrix.folder }}/haxe/
            export/${{ matrix.build }}/${{ matrix.folder }}/obj/
            .haxelib/
          restore-keys: |
            cache-${{ matrix.compile }}-${{ matrix.build }}