name: MacOS Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: MacOS Build
    permissions: write-all
    runs-on: macos-13

    steps:
      - uses: actions/checkout@main
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Restore action cache
        uses: actions/cache@main
        with:
          key: cache-build-mac
          path: |
            .haxelib/
            export/release/macos/haxe/
            export/release/macos/obj/
          restore-keys: |
            cache-build-mac

      - name: Installing/Updating libraries
        run: |
          haxe -cp commandline -D analyzer-optimize --run Main setup -s
      - name: Compile hxcpp
        run: |
          cd .haxelib/hxcpp/git/tools/run
          haxe compile.hxml
          cd ../hxcpp
          haxe compile.hxml
          cd ../../../../..

      - name: Compile
        run: haxelib run lime build mac

      - name: Tar files
        run: tar -zcvf AlterEngine.tar.gz -C export/release/macos/bin .

      - name: Uploading artifact
        uses: actions/upload-artifact@main
        with:
          name: Alter Engine
          path: AlterEngine.tar.gz
          if-no-files-found: error

      - name: Clearing already existing cache
        uses: actions/github-script@main
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-build-mac") {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log("Cache cleared.")
              }
            }

      - name: Uploading new cache
        uses: actions/cache@main
        with:
          key: cache-build-mac
          path: |
            .haxelib/
            export/release/macos/haxe/
            export/release/macos/obj/
          restore-keys: |
            cache-build-mac