name: MacOS Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: MacOS Build
    permissions: write-all
    runs-on: macos-13

    steps:
      - uses: actions/checkout@main
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Restore action cache
        id: cache-build-macos-restore
        uses: actions/cache/restore@main
        with:
          key: cache-build-macos
          path: |
            .haxelib/
            export/release/macos/haxe/
            export/release/macos/obj/

      - name: Installing/Updating libraries
        run: |
          haxe -cp commandline -D analyzer-optimize --run Main setup -s

      - name: Compile hxcpp
        run: |
          cd .haxelib/hxcpp/git/tools/run
          haxe compile.hxml
          cd ../hxcpp
          haxe compile.hxml
          cd ../../../../..

      - name: Compile
        run: haxelib run lime build mac

      - name: Tar files
        run: tar -zcvf AlterEngine.tar.gz -C export/release/macos/bin .

      - name: Uploading artifact
        uses: actions/upload-artifact@main
        with:
          name: Alter Engine
          path: AlterEngine.tar.gz
          if-no-files-found: error

      - name: Clearing already existing cache
        uses: actions/github-script@main
        with:
          script: |
            try {
            	const caches = await github.rest.actions.getActionsCacheList({
            		owner: context.repo.owner,
            		repo: context.repo.repo,
            	})
            	if (typeof caches.data.actions_caches != null && caches.data.actions_caches.length > 0) {
            		for (const cache of caches.data.actions_caches) {
            			if (cache.key == "cache-build-macos") {
            				console.log('Clearing ' + cache.key + '...')
            				await github.rest.actions.deleteActionsCacheById({
            					owner: context.repo.owner,
            					repo: context.repo.repo,
            					cache_id: cache.id,
            				})
            				console.log("Cache cleared.")
            			}
            		}
            	}
            } catch (error) {
            	console.log(error.message);
            }

      - name: Uploading new cache
        id: cache-build-macos-save
        uses: actions/cache/save@main
        with:
          key: cache-build-macos
          path: |
            .haxelib/
            export/release/macos/haxe/
            export/release/macos/obj/